from win32 import win32gui, win32api
import os
import json
all = 0
cwd = os.getcwd()
with open(os.path.join(cwd, "config.json"), "r", encoding="utf-8")as f:
    all = json.load(f)
# except:
#     print("cant load configurations, exit")
# PATH
BUDDY_ROOT_PATH = all["BUDDY_ROOT_PATH"]
CLIENT_PATH = all["CLIENT_PATH"]
BUDDY_PATH = os.path.join(BUDDY_ROOT_PATH, "start.bat")

BUDDY_VERIFY_PATH = os.path.join(BUDDY_ROOT_PATH, "auto.exe")
BUDDY_STAT_PATH = os.path.join(BUDDY_ROOT_PATH, r"Settings\Default\Stats.json")
LOGS_PATH = os.path.join(BUDDY_ROOT_PATH, "Logs")
CLIENT_LOGIN_WINDOW_NAME = all["CLIENT_LOGIN_WINDOW_NAME"]
CLIENT_WINDOW_NAME = all["CLIENT_WINDOW_NAME"]
GAME_WINDOW_NAME = all["GAME_WINDOW_NAME"]
BUDDY_WINDOW_NAME = all["BUDDY_WINDOW_NAME"]
PYHL_NAME="HL"

SCREEN_WIDTH = win32api.GetSystemMetrics(0)
SCREEN_HEIGHT = win32api.GetSystemMetrics(1)
LOGIN_ACCOUT_CLICK_POS = (35, 200)
LOGIN_PASSWORD_CLICK_POS = (35, 245)
LOGIN_ENTER_CLICK_POS = (180, 330)
CLIENT_POS = (-270, -500, 0, 0)
CLIENT_LOGIN_POS = (0, 0, 0, 0)
CLIENT_CLICK_POS = (10, 10)
GAME_WIDTH = 200
GAME_HEIGHT = 150
GAME_POS = (SCREEN_WIDTH-GAME_WIDTH, 0, GAME_WIDTH, GAME_HEIGHT)
BUDDY_WIDTH = all["BUDDY_WIDTH"]
BUDDY_HEIGHT = all["BUDDY_HEIGHT"]

BUDDY_POS = (0, 0, BUDDY_WIDTH, BUDDY_HEIGHT)
BUDDY_CLICK_POS = (BUDDY_POS[0]+BUDDY_WIDTH-22, BUDDY_POS[1]+103)
BUDDY_VERIFY_POS =(876,502)
BUDDY_CONFIRM_POS =(904,407)
ACCOUNTS = all["ACCOUNTS"]
ACTIVE_ACCOUNT = all["ACTIVE_ACCOUNT"]-1
CURRENT_ACCOUNT = ACCOUNTS[ACTIVE_ACCOUNT]["ACCOUNT"]
CURRENT_PASSWORD = ACCOUNTS[ACTIVE_ACCOUNT]["PASSWORD"]

# Delay
NORMAL_DELAY = all["NORMAL_DELAY"]
CLIENT_DELAY = all["CLIENT_DELAY"]
LOGIN_DELAY = all["LOGIN_DELAY"]
BUDDY_START_DELAY = all["BUDDY_START_DELAY"]
GAME_START_DELAY = all["GAME_START_DELAY"]
TIME_PER_GAME = all["TIME_PER_GAME"]
# 勾选自投
AUTO_CONCEDE_POS = (BUDDY_POS[0]+162, BUDDY_POS[1]+444)
AUTO_CONCEDE_ENABLE = all["AUTO_CONCEDE_ENABLE"]

# 进入设置界面
CONFIG_POS = (BUDDY_POS[0]+90, BUDDY_POS[1]+139)
USER_POS = (BUDDY_POS[0]+83, BUDDY_POS[1]+158)
